[package]
name = "hello_remote_world"
version = "0.1.0"
authors = ["John Torres"]
edition = "2021"

[lib]
path ="./src/lib/lib.rs"

[dependencies]
csv = "1.3.0"
plotly = "0.9.1"
polars = "0.42.0"
rustworkx-core = "0.15.1"


